name = "LFTCM2026"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LFTCM2026"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
linter.unusedVariables = false
linter.unusedTactic = false # proofs here end with `done`, which the linter calls unused
linter.overlappingInstances = false
linter.style.openClassical = false
warn.classDefReducibility = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "LFTCM2026"
