name = "LFTCM2026"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LFTCM2026"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
weak.linter.mathlibStandardSet = true
linter.unusedVariables = false
linter.overlappingInstances = false
linter.style.openClassical = false
warn.classDefReducibility = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.34.0-rc1"

[[lean_lib]]
name = "LFTCM2026"
